* 准备工作
** 获取LinkedME Key
新用户：在官网网站注册账号，注册后创建应用，在后台导航栏“设置”中查看LinkedME Key。
老用户：已经在官网网站注册账号，直接创建应用（可以创建多个应用），直接到导航栏“设置”中查看LinkedME Key。
** 获取LinkedME Android SDK及Demo
到官方网站下载LinkedME-Android-Deep-Linking-SDK，下载 Demo工程，获取工程libs目录下的 LinkedME-Android-Deep-Linking-SDK-V1.0.*.jar支持包。
* 导入SDK
** 导入LinkedME Android SDK
* 基本配置
** 配置AndroidManifest.xml
*** 添加LinkedME Key
*** 添加访问权限
集成LinkedME SDK需要开启的访问权限
*** 添加URI Scheme和App Links支持
添加URI Scheme和App Links支持后，才能够通过这两种方式跳转到APP内
** 初始化LinkedME实例
** 配置URI Scheme唤起的Activity页面(例如：MainActivity)
此配置保证APP能正常跳转到特定详情页面
* 深度链接功能
本模块实现的功能是创建深度链接及通过深度链接跳转到APP内的详情页面，若想要使用如下功能，请务必将“基本配置”部分全部实现
** 创建深度链接
温馨提示：如果web端集成了web sdk，则无需客户端创建深度链接，本节无需集成。
通过SDK创建深度链接，例如在分享页面时，页面的链接是通过SDK生成的深度链接，当打开分享内容时就可以通过深度链接唤起APP并进入对应页面
** 解析深度链接
通过深度链接唤起APP时，解析深度链接携带的参数以打开对应页面
* 用户行为追踪
Track是追踪用户APP内行为的工具，这里的用户行为既可以是APP内页面浏览的次数，也可以是启动APP的次数，还可以是用户在APP内的任何点击行为，例如图片下载、音乐播放、文章分享等，甚至是APP内某种逻辑的判断，都可以通过Track来追踪。
针对不同行为，您还可以添加具体的特征描述，例如下载图片的类型，播放音乐的流派，分享文章的作者等。
** 使用Track功能
Track功能适用于Android 2.3及以上操作系统的设备。系统提供三个标准效果点，如果不能满足您的监测需求，还可以自定义效果点
* 其他功能
** 测试模式
若想测试集成SDK后是否能正确生成并解析深度链接，可以使用测试模式。测试模式需要先在后台中注册您的测试设备，测试设备产生的数据将进入测试系统（Test）中。
